### PR TITLE
Linus had some contributions

### PR DESCRIPTION
**Pull request by Laursen79**
I am excited to submit this pull request which contains significant improvements to our product. I have invested a great deal of time and effort into this update, and I believe that the changes I have made will have a positive impact on the overall functionality and usability of the product.

Firstly, I have implemented several new features that will enhance the user experience and streamline the workflow. These features include a more intuitive navigation menu, improved search functionality, and a redesigned user interface that is both aesthetically pleasing and user-friendly.

Additionally, I have addressed several bugs and issues that were affecting the performance of the product. These fixes will ensure that the product is more reliable and stable, and will reduce the likelihood of errors and crashes.

Furthermore, I have conducted extensive testing to ensure that these improvements are compatible with a wide range of systems and devices. I am confident that these changes will enhance the performance and reliability of the product, and will make it more accessible to a wider audience.

In summary, I believe that the changes I have made will significantly improve the product and provide tangible benefits to our users. Thank you for taking the time to review this pull request, and I look forward to your feedback.

Best regards,

Simon Laursen

### CODE REVIEW

**Review by JE-FH — COMMENTED** [review]
This is good i think

**Comment by JE-FH** [comment]
I would like if any of you could look at it@MJHC @alexsteffensen

**Comment by Laursen79** [comment]
Maybe @t-lohse should look at this?

**Comment by JE-FH** [comment]
@KiraStaehr we need your opinion on this

**Comment by MJHC** [comment]
bitmoji

**Comment by Laursen79** [comment]
automa-thomas

This contribution was really good 👍🏿

**Review by t-lohse — COMMENTED** [review]
I think `automa-thomas` needs an additional (HUGE) state between the two in the bottom, with two edges: one from the middle to it, and the other way around

**Comment by alexsteffensen** [comment]
This is pretty fucking based...

**Comment by Laursen79** [comment]
automa-thomas

@t-lohse, were you thinking something like this?

**Comment by t-lohse** [comment]
image

**Review by t-lohse — COMMENTED** [review]
image

**Comment by Laursen79** [comment]
Ready for review 👍🏿

**Comment by JE-FH** [comment]
Why was this closed?

**Comment by Laursen79** [comment]
Please reopen, the issue is NOT FIXED

**Pull request closed without merging**
